### PR TITLE
Release prep 1.8.0

### PR DESCRIPTION
**Pull request by webketje**

### CODE REVIEW

**Comment by webketje** [comment]
@RobLoach I think you confused the Twig lib version with the jstransformer version in the latest tag. It goes 1.7.0 -> 1.16.0. Or was it intentional?

**Comment by RobLoach** [comment]
I think having them roughly match could help people understand the version that's used.

**Comment by RobLoach** [comment]
Also, I've seen a few warnings when using this in a couple applications. Is it working for you?

**Comment by webketje** [comment]
> I think having them roughly match could help people understand the version that's used.

`@storybook` addons use this model, but the difference is that storybook has control over those addons and an in-sync release process. For jstransformers the versioning is bound to get out-of-sync or limit the ability to improve the jstransformer. I would argue that departing from semver is not worth the benefit of not having to look up the version of the templating lib dependency, should the need arise. At the very least it should be prominently displayed in the README: 

_This project **does not adhere to semantic versioning**. Instead it tracks the major version of the jstranformer main dependency_

> Also, I've seen a few warnings when using this in a couple applications. Is it working for you?

I haven't followed up in a while, I don't remember if I tested it on a more elaborate use case than the repo's tests.

**Comment by RobLoach** [comment]
I'm down with that docs change... https://github.com/jstransformers/jstransformer-twig/pull/42

**Pull request merged**
